name: pullRequest
run-name: ${{ github.actor }} making pull request
on: 
  pull_request:
    branches: master
jobs:
  install_and_test:
    runs-on: ubuntu-latest
    outputs:
      exitcode: ${{ steps.tests.outputs.exitcode }}
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16.20.1'
          cache: 'npm'
      - run: npm ci
      - run: npm run test-ci
      - name: tests
        id: tests
        run: echo "exitcode=$?" >> $GITHUB_OUTPUT
        continue-on-error: true

      - name: Archive code coverage results
        uses: actions/upload-artifact@v3
        with:
          name: test-report
          path: test-report.html

  commitlint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: wagoid/commitlint-github-action@v4
  
  checkPR:
    runs-on: ubuntu-latest
    needs: [ install_and_test, commitlint ]
    steps:
      - if: needs.install_and_test.outputs.exitcode == 1
        uses: superbrothers/close-pull-request@v3
        with:
          comment: "Тесты не прошли"