name: release
run-name: ${{ github.actor }} is releasing
on: 
  pull_request:
    branches: master
  push:
    branches: master
jobs:
  install_and_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16.20.1'
          cache: 'npm'
      - run: npm ci
      - run: npm run test-ci
      - name: Archive code coverage results
        uses: actions/upload-artifact@v3
        with:
          name: test-report
          path: test-report.html
          
  commitlint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: wagoid/commitlint-github-action@v4