name: release
run-name: ${{ github.actor }} is releasing
on: 
  pull_request:
    branches: master
  push:
    tags: 
      - 'v\d+'
      
permissions:
  contents: read
  issues: write

jobs:
  install_and_test:
    runs-on: ubuntu-latest
    outputs:
      exitcode: ${{ steps.tests.outputs.exitcode }}
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16.20.1'
          cache: 'npm'
      - run: npm ci
      - run: npm run test-ci
      - name: tests
        id: tests
        run: echo "exitcode=$?" >> $GITHUB_OUTPUT
        continue-on-error: true

      - name: Archive code coverage results
        uses: actions/upload-artifact@v3
        with:
          name: test-report
          path: test-report.html
          
  commitlint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: wagoid/commitlint-github-action@v4
  
  release:
    runs-on: ubuntu-latest
    needs: [ install_and_test ]
    steps:
      - name: Get tag
        id: tag
        uses: little-core-labs/get-git-tag@v3.0.1
      - name: Get current date
        id: date
        run: echo "::set-output name=date::$(date +'%Y-%m-%d')"
      - name: Create Release Issue
        uses: dacbd/create-issue-action@main
        with:
          token: ${{ github.token }}
          title: Release `${{ steps.tag.outputs.tag }}`
          labels: RELEASE
          body: |
            ### Context
            Author -        `${{ github.actor }}`
            Version -       `${{ steps.tag.outputs.tag }}`
            Date -          `${{ steps.date.outputs.date }}`
      - name: Changelog
        uses: scottbrenner/generate-changelog-action@master
        id: Changelog

  closeIssue:
    runs-on: ubuntu-latest
    needs: [ install_and_test, release ]
    steps:
      - name: Find the last open issue
        id: last-issue
        uses: micalevisk/last-issue-action@v2
        with:
          state: open
          # Find the last updated open issue that has these labels:
          labels: |
            RELEASE

      - if: needs.install_and_test.outputs.exitcode == 0
        name: Close Issue
        uses: peter-evans/close-issue@v3
        with:
          issue-number: ${{steps.last-issue.outputs.issue-number}}
          comment: Auto-closing issue
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
