name: release
run-name: ${{ github.actor }} is releasing
on: 
  pull_request:
    branches: master
  push:
    branches: master
    tags: 
      - 'v\d+'
      
permissions:
  contents: read
  issues: write

jobs:
  install_and_test:
    runs-on: ubuntu-latest
    outputs:
      exitcode: ${{ steps.tests.outputs.exitcode }}
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16.20.1'
          cache: 'npm'
      - run: npm ci
      - run: npm run test-ci
      - name: tests
        id: tests
        run: echo "exitcode=$?" >> $GITHUB_OUTPUT
        continue-on-error: true

      - name: Archive code coverage results
        uses: actions/upload-artifact@v3
        with:
          name: test-report
          path: test-report.html
          
  commitlint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: wagoid/commitlint-github-action@v4
  
  release:
    runs-on: ubuntu-latest
    needs: [ install_and_test ]
    steps:
      - name: Get tag
        id: tag
        uses: dawidd6/action-get-tag@v1
      - name: Create Release Issue
        uses: dacbd/create-issue-action@main
        with:
          token: ${{ github.token }}
          title: Release
          body: |
            ### Context
            Version -       `${{ steps.tag.outputs.tag }}`
            Workflow name - `${{ github.workflow }}`
      - uses: actions/github-script@v6
        with:
          script: |
            github.rest.issues.addLabels({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              labels: ["RELEASE"]
            })

      - if: needs.install_and_test.outputs.exitcode == 0
        name: Close Issue
        run: gh issue close --comment "Auto-closing issue"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Changelog
        uses: scottbrenner/generate-changelog-action@master
        id: Changelog